import{S as m,i as a}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const n of e.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function i(t){if(t.ep)return;t.ep=!0;const e=r(t);fetch(t.href,e)}})();const c=document.querySelector(".img-list");function d(s){console.log(s);const o=s.hits.map(r=>`<li class="list-el">
                <a href="${r.largeImageURL}"><img src='${r.webformatURL}' alt='${r.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${r.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${r.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${r.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${r.downloads}</p></div>
                </div>
            </li>`).join("");c.textContent="",c.insertAdjacentHTML("beforeend",o),new m(".gallery a")}document.querySelector(".span");function u(s){const o="https://pixabay.com",r="/api/",i=new URLSearchParams({key:"44411802-6a5316a8fc33c8235d915a6fe",image_type:"photo",orientation:"horizontal",safesearch:!0,q:`${s}`}),t=`${o}${r}?${i}`;fetch(t).then(e=>{if(e.ok)return e.json();throw new Error(e.status)}).then(e=>{if(e.length===0)throw new Error("Error! Nothing to load");d(e)}).catch(e=>{a.error({title:"Sorry,",message:"there are no images matching your search query. Please try again!",color:"red"})})}document.querySelector(".input-search");document.querySelector(".btn-search");const l=document.querySelector(".form-el");l.addEventListener("submit",s=>{s.preventDefault();const o=l.elements[0].value.trim();if(o)u(o);else{a.error({message:"Info Search input must be filled!"});return}});
//# sourceMappingURL=commonHelpers.js.map
