import{i as l}from"./assets/vendor-ad859c2f.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function a(i,s){console.log(i);const n=i.hits.map(r=>`<li>
                <a href="${r.largeImageURL}"><img src='${r.webformatURL}' alt='${r.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${r.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${r.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${r.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${r.downloads}</p></div>
                </div>
            </li>`).join("");s.textContent="",s.insertAdjacentHTML("beforeend",n)}function m(i,s){const n="https://pixabay.com",r="/api/",e=new URLSearchParams({key:"44411802-6a5316a8fc33c8235d915a6fe",image_type:"photo",orientation:"horizontal",safesearch:!0,q:`${i}`}),t=`${n}${r}?${e}`;return fetch(t).then(o=>{if(o.ok)return o.json();throw new Error(o.status)}).then(o=>{if(o.hits||o.length===0)throw new Error("Error! Nothing to load");a(o,s)}).catch(o=>{l.error({title:"Sorry,",message:"there are no images matching your search query. Please try again!",color:"red"})})}document.querySelector(".input-search");document.querySelector(".btn-search");const c=document.querySelector(".form-el"),d=document.querySelector(".img-list");c.addEventListener("submit",i=>{i.preventDefault();const s=c.elements[0].value.trim();if(s)m(s,d);else{l.error({message:"Info Search input must be filled!"});return}});
//# sourceMappingURL=commonHelpers.js.map
